### PR TITLE
Take options into account in the Map component

### PR DESCRIPTION
**Pull request by vincent-lecrubier-skydio**

### CODE REVIEW

**Comment by tschaub** [comment]
Thanks for the suggested change, @vincent-lecrubier-skydio.  I'm adding some tests that will help assert that this is doing the right thing.  Can you describe what problem you encountered that lead to this change?  I'd like to add tests that cover this.

**Comment by vincent-lecrubier-skydio** [comment]
I wanted to specify Map controls myself in react, which would look like this:

```tsx
<Map options={{ controls: [] }}>
        <ZoomControl options={{ className: styles.olZoomControl }} />
</Map>
```

Explanation:

- Line 1: Set `controls: []` to have a map with no controls initially
- Line 2: Add ZoomControl myself using react, customizing it as I want.

Without this PR, the code above leads to having duplicate zoom controls (The default ones with default style, and the one I add manually)

With this PR this is fixed.

**Comment by tschaub** [comment]
> I wanted to specify Map controls myself in react, which would look like this:
> 
> ```tsx
> <Map options={{ controls: [] }}>
>         <ZoomControl options={{ className: styles.olZoomControl }} />
> </Map>
> ```

The way to do this currently would be to pass `controls={[]}` as a map prop and then to supply your custom control as a child.

```jsx
<Map controls={[]}>
  <Zoom options={{className: 'custom'}} />
</Map>
```

I've added a test to demonstrate that this works.

I think there was some reason that we did not initially pass the `options` from the map element to the constructor, but I can't recall what it was right now.  And it does feel like expected behavior.  So I've added a test to cover that as well.

**Review by tschaub — APPROVED** [review]

**Comment by tschaub** [comment]
Thanks for the contribution, @vincent-lecrubier-skydio.

**Pull request merged**
